CREATE TABLE CLASS_NUM(
    SCHOOL_CD CHAR(3), 
    CLASS_NUM VARCHAR(5),
    ENT_YEAR INT(10),
    TEACHER_ID VARCHAR(10), 
    COURSE_CD CHAR(3),
    PRIMARY KEY(SCHOOL_CD, CLASS_NUM, ENT_YEAR), 
);

CREATE TABLE SCHOOL(
    CD CHAR(3) PRIMARY KEY,
    NAME VARCHAR(20)
);

CREATE TABLE TEACHER(
    ID VARCHAR(10) PRIMARY KEY,
    PASSWORD VARCHAR(30),
    NAME VARCHAR(10),
    SCHOOL_CD CHAR(3)
);

CREATE TABLE SUBJECT(
    SCHOOL_CD CHAR(3),
    CD CHAR(3),
    NAME VARCHAR(20),

    PRIMARY KEY(SCHOOL_CD, CD), 
);

CREATE TABLE STUDENT(
    NO VARCHAR(10) PRIMARY KEY,
    NAME VARCHAR(10),
    ENT_YEAR INT(10),
    CLASS_NUM CHAR(3),
    IS_ATTEND BOOLEAN,
    SCHOOL_CD CHAR(3),
);

CREATE TABLE TEST(
    STUDENT_NO VARCHAR(10),
    SUBJECT_CD CHAR(3),
    SCHOOL_CD CHAR(10),
    NO INT(10),
    POINT INT(10),
    CLASS_NUM VARCHAR(5),

    PRIMARY KEY(STUDENT_NO, SUBJECT_CD, SCHOOL_CD,NO),
);

CREATE TABLE COURSE(
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20),
    SCHOOL_CD CHAR(10) NOT NULL,
    PRIMARY KEY(CD, SCHOOL_CD),     
);

-- CLASS_NUM --
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM, ENT_YEAR, TEACHER_ID, COURSE_CD)
VALUES('oom', '103', 2023, 'admin', 'ASD');

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM, ENT_YEAR, TEACHER_ID, COURSE_CD)
VALUES('oom', '203', 2024, 'admin2', 'JKL');

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM, ENT_YEAR, TEACHER_ID, COURSE_CD)
VALUES('oom', '103', 0, null, null);

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM, ENT_YEAR, TEACHER_ID, COURSE_CD)
VALUES('oom', '203', 0, null, null);

-- SCHOOL --
INSERT INTO SCHOOL(CD, NAME)
VALUES('oom', '大宮校');

-- STUDENT --
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2310301', '瀬戸内寂聴', 2023, '103', FALSE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2310302', '瀬戸内暄聴', 2023, '103', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2320301', '大原太郎', 2023, '203', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2320302', '大原次郎', 2023, '203', FALSE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2320303', '大原三郎', 2023, '203', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2410301', '芥川龍之介', 2024, '103', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2410302', '芥川竜之介', 2024, '103', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2420301', '夏目金之助', 2024, '203', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2420302', '夏目銀之助', 2024, '203', TRUE, 'oom');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('2420303', '夏目銅之助', 2024, '203', FALSE, 'oom');


-- SUBJECT --
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oom', 'A02', '国語');

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oom', 'B02', '社会');

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oom', 'C02', '数学');

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oom', 'D02', '理科');

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oom', 'E02', '英語');

-- TEACHER --
INSERT INTO TEACHER(ID, PASSWORD, NAME, SCHOOL_CD)
VALUES('admin2', 'password', '小野妹子', 'oom');

INSERT INTO TEACHER(ID, PASSWORD, NAME, SCHOOL_CD)
VALUES('admin', 'password', '中本毎彦', 'oom');

-- COURSE --
INSERT INTO COURSE(CD, NAME, SCHOOL_CD)
VALUES('ASD','システム開発','oom');

INSERT INTO COURSE(CD, NAME, SCHOOL_CD)
VALUES('JKL','AI・機械学習','oom');

-- TEST --
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310301', 'A02', 'oom', 1, 45, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310302', 'A02', 'oom', 1, 86, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2410301', 'A02', 'oom', 1, 12, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2410302', 'A02', 'oom', 1, 0, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310301', 'A02', 'oom', 2, 38, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2410301', 'A02', 'oom', 2, 99, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310301', 'B02', 'oom', 1, 24, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2410302', 'B02', 'oom', 1, 64, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310301', 'B02', 'oom', 2, 100, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2310302', 'B02', 'oom', 2, 85, '103');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2320301', 'A02', 'oom', 1, 33, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2320303', 'A02', 'oom', 1, 74, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2420301', 'A02', 'oom', 1, 66, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2420302', 'A02', 'oom', 1, 34, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2320301', 'A02', 'oom', 2, 0, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2320302', 'A02', 'oom', 2, 35, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2420302', 'A02', 'oom', 2, 100, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2320301', 'B02', 'oom', 1, 38, '203');

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2420303', 'B02', 'oom', 1, 97, '203');
