-- クラス番号
DROP TABLE CLASS_NUM IF EXISTS;

CREATE TABLE CLASS_NUM(
    SCHOOL_CD CHAR(3) NOT NULL,
    CLASS_NUM VARCHAR(5) NOT NULL,
    PRIMARY KEY(SCHOOL_CD, CLASS_NUM)
);

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('utm', '101');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('utm', '201');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('utm', '301');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('utm', '401');

INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('oha', '101');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('oha', '102');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('oha', '201');
INSERT INTO CLASS_NUM(SCHOOL_CD, CLASS_NUM)
VALUES('oha', '202');

 
-- ---------------------------------------------------------

-- 学生
DROP TABLE STUDENT IF EXISTS;

CREATE TABLE STUDENT(
    NO          CHAR(10) NOT NULL PRIMARY KEY,
    NAME        VARCHAR(10) DEFAULT NULL,
    ENT_YEAR    INT DEFAULT NULL,
    CLASS_NUM   CHAR(5) DEFAULT NULL,
    IS_ATTEND   BOOL DEFAULT NULL,
    SCHOOL_CD   CHAR(6) DEFAULT NULL
);

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0221011', '宇都宮22太郎', 2022, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0221012', '宇都宮22馬郎', 2022, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0221013', '宇都宮22人狼', 2022, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0221014', '宇都宮22大宮', 2022, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0221015', '宇都宮22千太朗', 2022, '101', TRUE, 'utm');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0222011', '宇都宮22次郎', 2022, '201', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0223011', '宇都宮22三郎', 2022, '301', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0224011', '宇都宮22四郎', 2022, '401', false, 'utm');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0231011', '宇都宮23太郎', 2023, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0232011', '宇都宮23次郎', 2023, '201', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0233011', '宇都宮23三郎', 2023, '301', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0234011', '宇都宮23四郎', 2023, '401', false, 'utm');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0241011', '宇都宮24太郎', 2024, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0242011', '宇都宮24次郎', 2024, '201', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0243011', '宇都宮24三郎', 2024, '301', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0244011', '宇都宮24四郎', 2024, '401', FALSE, 'utm');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0251011', '宇都宮25太郎', 2025, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0252011', '宇都宮25次郎', 2025, '201', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0253011', '宇都宮25三郎', 2025, '301', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0254011', '宇都宮25四郎', 2025, '401', false, 'utm');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0251011', '宇都宮26太郎', 2026, '101', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0252011', '宇都宮26次郎', 2026, '201', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0253011', '宇都宮26三郎', 2026, '301', TRUE, 'utm');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('0254011', '宇都宮26四郎', 2026, '401', false, 'utm');


INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9231011', '大原23太郎', 2023, '101', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9231021', '大原23次郎', 2023, '102', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9232011', '大原23三郎', 2023, '201', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9232021', '大原23四郎', 2023, '202', false, 'oha');

INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9241011', '大原24一子', 2024, '101', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9241021', '大原24二子', 2024, '102', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9242011', '大原24三子', 2024, '201', TRUE, 'oha');
INSERT INTO STUDENT(NO, NAME, ENT_YEAR, CLASS_NUM, IS_ATTEND, SCHOOL_CD)
VALUES('9242021', '大原24四子', 2024, '202', FALSE, 'oha');

-- ---------------------------------------------------------
 
-- 学校
DROP TABLE SCHOOL IF EXISTS;

CREATE TABLE SCHOOL(
    CD CHAR(3) NOT NULL PRIMARY KEY,
    NAME VARCHAR(20) DEFAULT NULL
);

INSERT INTO SCHOOL(CD, NAME) VALUES('utm', '宇都宮校');
INSERT INTO SCHOOL(CD, NAME) VALUES('oha', '大原校');
-- ---------------------------------------------------------

-- 科目
DROP TABLE SUBJECT IF EXISTS;

CREATE TABLE SUBJECT(
    SCHOOL_CD CHAR(3) NOT NULL,
    CD CHAR(3) NOT NULL,
    NAME VARCHAR(20) DEFAULT NULL,
    PRIMARY KEY(SCHOOL_CD, CD)
);

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('utm', 'AO1', '国語');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('utm', 'BO1', '数学');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('utm', 'CO1', '英語コミュニケーション概論');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('utm', 'DO1', '理科');

INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'AO1', '国語');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'BO1', '数学');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'CO1', '英語コミュニケーション概論');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'DO1', '理科');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'EO1', '情報処理基礎知識I');
INSERT INTO SUBJECT(SCHOOL_CD, CD, NAME)
VALUES('oha', 'FO1', 'Python1');
-- ---------------------------------------------------------

-- 試験
DROP TABLE TEST IF EXISTS;

CREATE TABLE TEST (
    STUDENT_NO    VARCHAR(10) NOT NULL,
    SUBJECT_CD    CHAR(3) NOT NULL ,
    SCHOOL_CD    CHAR (10) NOT NULL,
    NO    INTEGER(10) NOT NULL,
    POINT    INTEGER(10) DEFAULT NULL,
    CLASS_NUM   VARCHAR(5) DEFAULT NULL,
    PRIMARY KEY(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO)
);

INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355001', 'AO1', 'utm', '1', '100', '101');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355001', 'BO1', 'utm', '1', '90', '101');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355001', 'CO1', 'utm', '1', '80', '101');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355001', 'DO1', 'utm', '1', '70', '101');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355002', 'AO1', 'utm', '1', '30', '201');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355002', 'BO1', 'utm', '1', '30', '201');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355003', 'CO1', 'utm', '1', '70', '301');
INSERT INTO TEST(STUDENT_NO, SUBJECT_CD, SCHOOL_CD, NO, POINT, CLASS_NUM)
VALUES('2355004', 'DO1', 'utm', '1', '90', '401');
 
-- ---------------------------------------------------------

-- 職員テーブル
DROP TABLE TEACHER IF EXISTS;

CREATE TABLE TEACHER (
    ID  VARCHAR(10) NOT NULL PRIMARY KEY,
    PASSWORD VARCHAR(30) DEFAULT NULL,
    NAME VARCHAR(10) DEFAULT NULL,
    SCHOOL_CD CHAR(3) DEFAULT NULL
);

INSERT INTO TEACHER(ID, PASSWORD, NAME, SCHOOL_CD)
VALUES('utunomiya', 'password', '宇都宮講師', 'utm');
INSERT INTO TEACHER(ID, PASSWORD, NAME, SCHOOL_CD)
VALUES('oohara', 'password', '大原大臣', 'oha');